# fly.toml app configuration file generated for myskybridge-nameless-log-2055 on 2024-10-19T13:07:53-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'myskybridge-nameless-log-2055'
primary_region = 'ord'

[build]

[env]
  FLY_SWAP = 'true'
  SKYBRIDGE_BASEURL = 'myskybridge-nameless-log-2055.fly.dev'
  SKYBRIDGE_SHOW_INDEX = 'true'

[[mounts]]
  source = 'skybridge_data'
  destination = '/app/database'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 999999
    soft_limit = 9999

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '30s'
    method = 'GET'
    path = '/api/v2/instance'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  
